name: SSH Handshaking

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: pub-pri Handshaking
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            rm -rf notes-app

            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
            \. "$HOME/.nvm/nvm.sh"
            nvm install 20.20.2

            git clone https://github.com/sauvikchatterjee07/notes-app.git

            cd notes-app/frontend

            npm install

            sudo apt update
            sudo apt install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx

            npm run build
            sudo cp -r dist/* /var/www/html/
